version: '3.8'

services:
  neo4j:
    image: neo4j:5.24.2-community
    container_name: neo4j-hw3
    restart: always
    environment:
      NEO4J_AUTH: neo4j/your_password
    ports:
      - "7474:7474" # HTTP Neo4j Browser
      - "7687:7687" # Bolt protocol (used by drivers)
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hw3-knowledge-graph
    restart: always
    depends_on:
      - neo4j
    volumes:
      - .:/app
    ports:
      - "8000:8000" # If your Python app exposes an API
    environment:
      - NEO4J_URI=bolt://neo4j_db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=your_password

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: